name: "Draft Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-draft:
    name: "Update Draft Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Read version from gradle.properties"
        id: version
        shell: bash
        # language=bash
        run: |
          version=$(grep '^dev.sanson.spacetimedb.version=' gradle.properties | cut -d'=' -f2)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: "Update release"
        id: update
        env:
          TAG: "v${{ steps.version.outputs.tag }}"
          GH_TOKEN: ${{ github.token }}
        shell: bash
        # language=bash
        run: |
          gh release delete "${TAG}" --yes || true
          link=$(gh release create "${TAG}" --generate-notes --latest --draft)
          echo "::notice title=Release ${TAG} drafted::${link}"